name: Match Notification Scheduler

on:
  schedule:
    - cron: '0 7 * * *'  # Runs at 7:00 AM daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  schedule-matches:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot pytz
    
    - name: Run Match Scheduler
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python match_scheduler.py
